# Machine Learning Workflow
Complete the steps below to complete the machine learning workflow for this classifier.

In [17]:
import nltk
nltk.download(['punkt', 'wordnet'])

[nltk_data] Downloading package punkt to
[nltk_data]     /Users/jinchaochen/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     /Users/jinchaochen/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


True

In [18]:
import re
import pandas as pd
from nltk.tokenize import word_tokenize
from nltk.stem import WordNetLemmatizer
from nltk.corpus import stopwords

from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.feature_extraction.text import TfidfVectorizer

import numpy as np

In [19]:
url_regex = 'http[s]?://(?:[a-zA-Z]|[0-9]|[$-_@.&+]|[!*\(\),]|(?:%[0-9a-fA-F][0-9a-fA-F]))+'

def load_data():
    df = pd.read_csv('corporate_messaging.csv', encoding='latin-1')
    df = df[(df["category:confidence"] == 1) & (df['category'] != 'Exclude')]
    X = df.text.values
    y = df.category.values
    return X, y

def tokenize(text):
    detected_urls = re.findall(url_regex, text)
    for url in detected_urls:
        text = text.replace(url, "urlplaceholder") 

    tokens = word_tokenize(text)
    lemmatizer = WordNetLemmatizer()

    clean_tokens = []
    for tok in tokens:
        clean_tok = lemmatizer.lemmatize(tok).lower().strip()
        clean_tokens.append(clean_tok)
        
    # remove stop words
    stop_words = stopwords.words('english')
    clean_tokens = [w for w in clean_tokens if not w in stop_words] 

    return clean_tokens

### Step 1: Load data and perform a train test split

### Step 2: Train classifier
* Fit and transform the training data with `CountVectorizer`. Hint: You can include your tokenize function in the `tokenizer` keyword argument!
* Fit and transform these word counts with `TfidfTransformer`.
* Fit a classifier to these tfidf values.

### Step 3: Predict on test data
* Transform (no fitting) the test data with the same CountVectorizer and TfidfTransformer
* Predict labels on these tfidf values.

### Step 4: Display results
Display a confusion matrix and accuracy score based on the model's predictions.

# Final Step: Refactor
Organize these steps into the following functions.

In [20]:
def display_results(y_test, y_pred):
    # insert step 4 here
    labels = np.unique(y_test)
    confusion_mat = confusion_matrix( y_test, y_pred)
    accuracy = accuracy_score(y_test, y_pred)

    print("Labels:", labels)
    print("Confusion Matrix:\n", confusion_mat)
    print("Accuracy:", accuracy)


def main():
    # step1: load and split data
    X, y = load_data()
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33)
    
    # step2: transform input data
    vect = TfidfVectorizer(tokenizer=tokenize)
    tfidf_matrix_train = vect.fit_transform(X_train)

    clf = RandomForestClassifier()
    clf.fit(tfidf_matrix_train.toarray(),y_train)

    # step3: 
    tfidf_matrix_test = vect.transform(X_test)
    y_pred = clf.predict(tfidf_matrix_test.toarray())
    
    display_results(y_test, y_pred)

In [21]:
# run program
main()

Labels: ['Action' 'Dialogue' 'Information']
Confusion Matrix:
 [[102   0  42]
 [  2  31   8]
 [  4   2 602]]
Accuracy: 0.926860025220681
